import type {
  Conversation,
  CriterionDef,
  CriterionId,
  Developer,
  Repository,
  TraceRun,
} from "./types";

export const ORG = "acme";

export const CRITERIA: CriterionDef[] = [
  {
    id: "readability",
    label: "Readability",
    defaultWeight: 0.1,
    signals: "Naming, function length, nesting, comment density",
  },
  {
    id: "documentation",
    label: "Documentation",
    defaultWeight: 0.08,
    signals: "README, API docs, docstrings, architecture notes",
  },
  {
    id: "modularity",
    label: "Modularity",
    defaultWeight: 0.12,
    signals: "Layering, cohesion, cyclic imports, duplication",
  },
  {
    id: "error_handling",
    label: "Error Handling",
    defaultWeight: 0.1,
    signals: "Bare excepts, timeouts, unvalidated HTTP",
  },
  {
    id: "security",
    label: "Security",
    defaultWeight: 0.15,
    signals: "Secrets, injection, authz, dangerous APIs, CVEs",
  },
  {
    id: "test_coverage",
    label: "Test Coverage",
    defaultWeight: 0.12,
    signals: "Tests present, assertions, CI job, coverage.xml",
  },
  {
    id: "performance",
    label: "Performance",
    defaultWeight: 0.08,
    signals: "N+1, unbounded loops, pagination, sync I/O",
  },
  {
    id: "maintainability",
    label: "Maintainability",
    defaultWeight: 0.1,
    signals: "Complexity, TODOs, dead code, typing, churn",
  },
  {
    id: "standards",
    label: "Standards",
    defaultWeight: 0.08,
    signals: "Linters, CI, commits, license, editorconfig",
  },
  {
    id: "innovation",
    label: "Innovation",
    defaultWeight: 0.07,
    signals: "Architecture, algorithms, DX, unusual patterns",
  },
];

export const CRITERION_IDS = CRITERIA.map((c) => c.id);

const emptyScores = (fill: number): Record<CriterionId, number> =>
  Object.fromEntries(CRITERION_IDS.map((id) => [id, fill])) as Record<
    CriterionId,
    number
  >;

function pack(
  values: Partial<Record<CriterionId, number>> & { rest?: number },
): Record<CriterionId, number> {
  const rest = values.rest ?? 72;
  const base = emptyScores(rest);
  for (const id of CRITERION_IDS) {
    if (values[id] != null) base[id] = values[id]!;
  }
  return base;
}

export const DEVELOPERS: Developer[] = [
  {
    id: "dev-alex",
    githubLogin: "alex-rivers",
    displayName: "Alex Rivers",
    initials: "AR",
    title: "Staff backend",
    commitCount: 412,
    linesAdded: 48120,
    lastCommitAt: "2026-09-07T18:12:00Z",
    repoIds: ["payments-api", "identity-svc", "fraud-engine"],
    overall: 88,
    scores: pack({
      security: 92,
      modularity: 90,
      error_handling: 86,
      performance: 84,
      test_coverage: 81,
      readability: 85,
      maintainability: 88,
      documentation: 74,
      standards: 86,
      innovation: 79,
    }),
  },
  {
    id: "dev-priya",
    githubLogin: "priya-nair",
    displayName: "Priya Nair",
    initials: "PN",
    title: "Frontend lead",
    commitCount: 298,
    linesAdded: 33210,
    lastCommitAt: "2026-09-08T09:40:00Z",
    repoIds: ["checkout-web", "design-system", "mobile-wallet"],
    overall: 84,
    scores: pack({
      readability: 93,
      documentation: 88,
      standards: 90,
      innovation: 86,
      modularity: 81,
      maintainability: 83,
      test_coverage: 77,
      security: 71,
      error_handling: 76,
      performance: 80,
    }),
  },
  {
    id: "dev-sam",
    githubLogin: "sam-okonkwo",
    displayName: "Sam Okonkwo",
    initials: "SO",
    title: "Security engineer",
    commitCount: 186,
    linesAdded: 15440,
    lastCommitAt: "2026-09-06T14:02:00Z",
    repoIds: ["identity-svc", "fraud-engine", "payments-api"],
    overall: 90,
    scores: pack({
      security: 96,
      error_handling: 91,
      standards: 88,
      maintainability: 84,
      modularity: 82,
      test_coverage: 85,
      readability: 80,
      documentation: 78,
      performance: 76,
      innovation: 72,
    }),
  },
  {
    id: "dev-lena",
    githubLogin: "lena-park",
    displayName: "Lena Park",
    initials: "LP",
    title: "SET / QA",
    commitCount: 241,
    linesAdded: 19880,
    lastCommitAt: "2026-09-07T11:22:00Z",
    repoIds: ["payments-api", "checkout-web", "data-pipeline"],
    overall: 86,
    scores: pack({
      test_coverage: 95,
      error_handling: 88,
      standards: 91,
      readability: 82,
      maintainability: 85,
      modularity: 79,
      documentation: 81,
      security: 74,
      performance: 73,
      innovation: 70,
    }),
  },
  {
    id: "dev-noah",
    githubLogin: "noah-ike",
    displayName: "Noah Ike",
    initials: "NI",
    title: "Platform / DX",
    commitCount: 167,
    linesAdded: 22104,
    lastCommitAt: "2026-09-05T20:10:00Z",
    repoIds: ["data-pipeline", "design-system", "infra-tf"],
    overall: 81,
    scores: pack({
      innovation: 91,
      performance: 88,
      modularity: 84,
      maintainability: 80,
      documentation: 77,
      readability: 79,
      standards: 75,
      test_coverage: 68,
      error_handling: 72,
      security: 70,
    }),
  },
  {
    id: "dev-jordan",
    githubLogin: "jordan-vale",
    displayName: "Jordan Vale",
    initials: "JV",
    title: "Product engineer",
    commitCount: 94,
    linesAdded: 9800,
    lastCommitAt: "2026-09-04T16:48:00Z",
    repoIds: ["checkout-web", "mobile-wallet"],
    overall: 73,
    scores: pack({
      readability: 84,
      documentation: 80,
      innovation: 82,
      standards: 76,
      modularity: 70,
      maintainability: 71,
      test_coverage: 62,
      error_handling: 64,
      performance: 69,
      security: 61,
    }),
  },
];

function evidence(
  repo: string,
): import("./types").CriterionScore[] {
  const samples: import("./types").CriterionScore[] = [
    {
      criterion: "security",
      score: 0,
      confidence: 0.82,
      summary:
        "Authz is consistent on mutating routes; one interpolated query remains in a reporting helper.",
      findings: [
        {
          id: `${repo}-sec-1`,
          severity: "high",
          path: "api/reports.py",
          startLine: 41,
          endLine: 58,
          message: "SQL interpolated from request query on the ledger export path.",
          suggestion: "Bind parameters through the existing query builder.",
        },
        {
          id: `${repo}-sec-2`,
          severity: "medium",
          path: "internal/authz.go",
          startLine: 112,
          endLine: 140,
          message: "Role check is duplicated instead of using the shared guard.",
          suggestion: "Route all handlers through RequireScope.",
        },
      ],
    },
    {
      criterion: "test_coverage",
      score: 0,
      confidence: 0.77,
      summary:
        "CI runs unit tests; integration coverage is thin around webhook retries.",
      findings: [
        {
          id: `${repo}-test-1`,
          severity: "medium",
          path: "tests/webhooks.spec.ts",
          startLine: 1,
          endLine: 24,
          message: "Happy-path only; no timeout or replay fixtures.",
          suggestion: "Add idempotency and 5xx retry cases.",
        },
      ],
    },
    {
      criterion: "documentation",
      score: 0,
      confidence: 0.7,
      summary: "README is current; service contracts live only in code comments.",
      findings: [
        {
          id: `${repo}-doc-1`,
          severity: "low",
          path: "README.md",
          startLine: 1,
          endLine: 40,
          message: "Local run is documented; no failure-mode or SLO section.",
          suggestion: "Add a short operations appendix.",
        },
      ],
    },
    {
      criterion: "modularity",
      score: 0,
      confidence: 0.74,
      summary: "Clear api / domain split; one package is accumulating helpers.",
      findings: [
        {
          id: `${repo}-mod-1`,
          severity: "info",
          path: "pkg/util/misc.go",
          startLine: 1,
          endLine: 220,
          message: "Catch-all util module with mixed concerns.",
          suggestion: "Split by domain (money, time, http).",
        },
      ],
    },
  ];
  return samples;
}

export const REPOS: Repository[] = [
  {
    id: "payments-api",
    githubId: 8811201,
    org: ORG,
    name: "payments-api",
    fullName: "acme/payments-api",
    description: "Ledger, captures, and settlement for card and wallet rails.",
    language: "Go",
    defaultBranch: "main",
    headSha: "a3f91c2",
    lastCommitAt: "2026-09-07T18:12:00Z",
    connected: true,
    visibleToEmployers: true,
    status: "indexed",
    overall: 84,
    lastEvaluatedAt: "2026-09-07T19:02:00Z",
    fileCount: 412,
    contributorIds: ["dev-alex", "dev-sam", "dev-lena"],
    scores: pack({
      security: 78,
      modularity: 88,
      error_handling: 81,
      performance: 86,
      test_coverage: 80,
      readability: 84,
      maintainability: 85,
      documentation: 72,
      standards: 87,
      innovation: 74,
      rest: 80,
    }),
    evidence: evidence("payments-api"),
  },
  {
    id: "checkout-web",
    githubId: 8811202,
    org: ORG,
    name: "checkout-web",
    fullName: "acme/checkout-web",
    description: "Hosted checkout, wallet sheet, and merchant preview.",
    language: "TypeScript",
    defaultBranch: "main",
    headSha: "b12d90e",
    lastCommitAt: "2026-09-08T09:40:00Z",
    connected: true,
    visibleToEmployers: true,
    status: "indexed",
    overall: 79,
    lastEvaluatedAt: "2026-09-08T10:15:00Z",
    fileCount: 286,
    contributorIds: ["dev-priya", "dev-jordan", "dev-lena"],
    scores: pack({
      readability: 91,
      documentation: 84,
      standards: 88,
      innovation: 82,
      modularity: 77,
      maintainability: 80,
      test_coverage: 71,
      security: 68,
      error_handling: 73,
      performance: 76,
    }),
    evidence: evidence("checkout-web"),
  },
  {
    id: "identity-svc",
    githubId: 8811203,
    org: ORG,
    name: "identity-svc",
    fullName: "acme/identity-svc",
    description: "SSO, session minting, and org RBAC.",
    language: "Go",
    defaultBranch: "main",
    headSha: "c90aa11",
    lastCommitAt: "2026-09-06T14:02:00Z",
    connected: true,
    visibleToEmployers: true,
    status: "indexed",
    overall: 91,
    lastEvaluatedAt: "2026-09-06T15:40:00Z",
    fileCount: 198,
    contributorIds: ["dev-alex", "dev-sam"],
    scores: pack({
      security: 94,
      error_handling: 90,
      standards: 89,
      modularity: 91,
      maintainability: 88,
      test_coverage: 86,
      readability: 85,
      documentation: 80,
      performance: 84,
      innovation: 77,
    }),
    evidence: evidence("identity-svc"),
  },
  {
    id: "mobile-wallet",
    githubId: 8811204,
    org: ORG,
    name: "mobile-wallet",
    fullName: "acme/mobile-wallet",
    description: "iOS and Android wallet surface.",
    language: "Kotlin",
    defaultBranch: "main",
    headSha: "d44be09",
    lastCommitAt: "2026-09-03T12:00:00Z",
    connected: true,
    visibleToEmployers: true,
    status: "indexed",
    overall: 64,
    lastEvaluatedAt: "2026-09-03T13:20:00Z",
    fileCount: 340,
    contributorIds: ["dev-priya", "dev-jordan"],
    scores: pack({
      readability: 71,
      documentation: 58,
      standards: 62,
      innovation: 69,
      modularity: 60,
      maintainability: 63,
      test_coverage: 51,
      security: 67,
      error_handling: 59,
      performance: 72,
    }),
    evidence: evidence("mobile-wallet"),
  },
  {
    id: "data-pipeline",
    githubId: 8811205,
    org: ORG,
    name: "data-pipeline",
    fullName: "acme/data-pipeline",
    description: "Batch + streaming ledger analytics.",
    language: "Python",
    defaultBranch: "main",
    headSha: "e71cc4a",
    lastCommitAt: "2026-09-05T20:10:00Z",
    connected: true,
    visibleToEmployers: true,
    status: "indexed",
    overall: 71,
    lastEvaluatedAt: "2026-09-05T21:00:00Z",
    fileCount: 154,
    contributorIds: ["dev-noah", "dev-lena"],
    scores: pack({
      performance: 88,
      innovation: 84,
      modularity: 73,
      maintainability: 70,
      documentation: 66,
      readability: 74,
      standards: 68,
      test_coverage: 60,
      error_handling: 69,
      security: 64,
    }),
    evidence: evidence("data-pipeline"),
  },
  {
    id: "design-system",
    githubId: 8811206,
    org: ORG,
    name: "design-system",
    fullName: "acme/design-system",
    description: "Tokens, primitives, and merchant UI kit.",
    language: "TypeScript",
    defaultBranch: "main",
    headSha: "f02ab33",
    lastCommitAt: "2026-09-08T08:12:00Z",
    connected: true,
    visibleToEmployers: true,
    status: "indexed",
    overall: 88,
    lastEvaluatedAt: "2026-09-08T08:50:00Z",
    fileCount: 220,
    contributorIds: ["dev-priya", "dev-noah"],
    scores: pack({
      readability: 94,
      documentation: 90,
      standards: 93,
      innovation: 87,
      modularity: 86,
      maintainability: 85,
      test_coverage: 78,
      security: 80,
      error_handling: 82,
      performance: 81,
    }),
    evidence: evidence("design-system"),
  },
  {
    id: "fraud-engine",
    githubId: 8811207,
    org: ORG,
    name: "fraud-engine",
    fullName: "acme/fraud-engine",
    description: "Rule + model scoring for payment risk.",
    language: "Python",
    defaultBranch: "main",
    headSha: "aa19d0c",
    lastCommitAt: "2026-09-08T11:05:00Z",
    connected: true,
    visibleToEmployers: false,
    status: "evaluating",
    overall: 82,
    lastEvaluatedAt: "2026-09-01T16:00:00Z",
    fileCount: 176,
    contributorIds: ["dev-alex", "dev-sam"],
    scores: pack({
      security: 88,
      innovation: 90,
      performance: 83,
      modularity: 80,
      maintainability: 79,
      test_coverage: 76,
      error_handling: 81,
      readability: 77,
      documentation: 70,
      standards: 82,
    }),
    evidence: evidence("fraud-engine"),
  },
  {
    id: "infra-tf",
    githubId: 8811208,
    org: ORG,
    name: "infra-tf",
    fullName: "acme/infra-tf",
    description: "Org-wide Terraform for payments VPC and IAM.",
    language: "HCL",
    defaultBranch: "main",
    headSha: "bb88e21",
    lastCommitAt: "2026-08-29T09:00:00Z",
    connected: false,
    visibleToEmployers: false,
    status: "not_connected",
    overall: null,
    lastEvaluatedAt: null,
    fileCount: 64,
    contributorIds: ["dev-noah"],
    scores: null,
    evidence: [],
  },
];

export const CONVERSATIONS: Conversation[] = [
  {
    id: "c1",
    title: "Where is auth enforced?",
    scope: "acme/identity-svc",
    updatedAt: "2026-09-08T10:22:00Z",
    messages: [
      {
        id: "m1",
        role: "user",
        content: "Where is auth enforced?",
      },
      {
        id: "m2",
        role: "assistant",
        content:
          "Session minting and scope checks live in the identity service, not in each product API. Incoming requests must present a minted session; mutating routes call RequireScope before the handler body.[1] Public GETs on JWKS skip the guard by design.[2] Payments-api trusts the same session cookie and re-validates org membership on write paths.[3]",
        citations: [
          {
            n: 1,
            path: "internal/http/middleware.go",
            startLine: 48,
            endLine: 79,
            snippet:
              "func RequireScope(scope string) mux.Middleware {\n  return func(next http.Handler) http.Handler {\n    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {\n      sess := SessionFrom(r.Context())\n      if !sess.Has(scope) { writeDenied(w); return }\n      next.ServeHTTP(w, r)\n    })\n  }\n}",
            repo: "acme/identity-svc",
          },
          {
            n: 2,
            path: "internal/http/router.go",
            startLine: 22,
            endLine: 31,
            snippet:
              "r.Get(\"/.well-known/jwks.json\", keys.HandleJWKS) // public",
            repo: "acme/identity-svc",
          },
          {
            n: 3,
            path: "api/auth.py",
            startLine: 14,
            endLine: 36,
            snippet:
              "def require_org(handler):\n    def wrapped(req):\n        sess = decode_session(req)\n        if sess.org_id != req.org_id:\n            raise Forbidden()\n        return handler(req)\n    return wrapped",
            repo: "acme/payments-api",
          },
        ],
      },
    ],
  },
  {
    id: "c2",
    title: "Webhook retry behavior",
    scope: "acme/payments-api",
    updatedAt: "2026-09-07T16:04:00Z",
    messages: [
      {
        id: "m3",
        role: "user",
        content: "How do webhook retries work?",
      },
      {
        id: "m4",
        role: "assistant",
        content:
          "Retries are at-least-once with a 12-hour exponential backoff and an idempotency key stored per destination.[1] There is no dead-letter topic in this snapshot.",
        citations: [
          {
            n: 1,
            path: "internal/webhooks/retry.go",
            startLine: 60,
            endLine: 88,
            snippet:
              "backoff := min(12*time.Hour, time.Duration(1<<attempt)*time.Second)",
            repo: "acme/payments-api",
          },
        ],
      },
    ],
  },
];

export const TRACE_RUNS: TraceRun[] = [
  {
    id: "run-eval-payments",
    kind: "evaluate",
    label: "Evaluate acme/payments-api @ a3f91c2",
    createdAt: "2026-09-07T19:02:00Z",
    durationMs: 42800,
    spans: [
      {
        id: "s0",
        parentId: null,
        name: "orchestrator.evaluate",
        model: "—",
        tokensIn: 0,
        tokensOut: 0,
        latencyMs: 42800,
        status: "ok",
        startedOffsetMs: 0,
      },
      {
        id: "s1",
        parentId: "s0",
        name: "agent.security",
        model: "grok-4",
        tokensIn: 6400,
        tokensOut: 812,
        latencyMs: 9400,
        status: "ok",
        startedOffsetMs: 1200,
      },
      {
        id: "s2",
        parentId: "s0",
        name: "agent.test_coverage",
        model: "grok-4",
        tokensIn: 4100,
        tokensOut: 540,
        latencyMs: 7200,
        status: "ok",
        startedOffsetMs: 1400,
      },
      {
        id: "s3",
        parentId: "s0",
        name: "agent.modularity",
        model: "grok-4",
        tokensIn: 5200,
        tokensOut: 610,
        latencyMs: 8100,
        status: "ok",
        startedOffsetMs: 1800,
      },
      {
        id: "s4",
        parentId: "s0",
        name: "agent.readability",
        model: "grok-4",
        tokensIn: 3800,
        tokensOut: 420,
        latencyMs: 6100,
        status: "ok",
        startedOffsetMs: 2000,
      },
      {
        id: "s5",
        parentId: "s0",
        name: "rag_index.embed",
        model: "embed-v1",
        tokensIn: 18200,
        tokensOut: 0,
        latencyMs: 15400,
        status: "ok",
        startedOffsetMs: 22000,
      },
      {
        id: "s6",
        parentId: "s0",
        name: "aggregator.weights",
        model: "—",
        tokensIn: 0,
        tokensOut: 0,
        latencyMs: 40,
        status: "ok",
        startedOffsetMs: 40000,
      },
    ],
  },
  {
    id: "run-ask-auth",
    kind: "ask",
    label: "Ask · Where is auth enforced?",
    createdAt: "2026-09-08T10:22:00Z",
    durationMs: 2100,
    spans: [
      {
        id: "a0",
        parentId: null,
        name: "rag.retrieve",
        model: "embed-v1",
        tokensIn: 42,
        tokensOut: 0,
        latencyMs: 180,
        status: "ok",
        startedOffsetMs: 0,
      },
      {
        id: "a1",
        parentId: null,
        name: "rag.generate",
        model: "grok-4",
        tokensIn: 2800,
        tokensOut: 410,
        latencyMs: 1860,
        status: "ok",
        startedOffsetMs: 200,
      },
    ],
  },
];

export const ROLE_MATRIX: Record<string, Partial<Record<CriterionId, number>>> = {
  "Backend engineer": {
    modularity: 0.3,
    error_handling: 0.25,
    performance: 0.2,
    security: 0.25,
  },
  "Frontend engineer": {
    readability: 0.3,
    standards: 0.25,
    documentation: 0.25,
    innovation: 0.2,
  },
  "Security engineer": {
    security: 0.5,
    error_handling: 0.3,
    standards: 0.2,
  },
  "Tech lead": {
    maintainability: 0.3,
    documentation: 0.25,
    modularity: 0.25,
    standards: 0.2,
  },
  "QA / SET": {
    test_coverage: 0.45,
    error_handling: 0.3,
    standards: 0.25,
  },
};

export const ADMIN_USER = {
  id: "u-admin",
  githubLogin: "maya-chen",
  name: "Maya Chen",
  initials: "MC",
  role: "admin" as const,
};

export const EMPLOYER_USER = {
  id: "u-employer",
  githubLogin: "jordan-vale",
  name: "Jordan Vale",
  initials: "JV",
  role: "employer" as const,
};
