"""initial_schema

Revision ID: 319dccdcd390
Revises: 
Create Date: 2026-09-09 15:56:06.469027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '319dccdcd390'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('github_username', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_github_username'), 'users', ['github_username'], unique=True)
    op.create_table('repos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('github_repo_id', sa.Integer(), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('clone_url', sa.String(length=512), nullable=False),
    sa.Column('default_branch', sa.String(length=100), server_default='main', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_repo_id', name='uq_repos_github_repo_id')
    )
    op.create_index(op.f('ix_repos_github_repo_id'), 'repos', ['github_repo_id'], unique=False)
    op.create_index(op.f('ix_repos_repo_name'), 'repos', ['repo_name'], unique=False)
    op.create_index('ix_repos_user_id', 'repos', ['user_id'], unique=False)
    op.create_table('code_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_chunks_file_path'), 'code_chunks', ['file_path'], unique=False)
    op.create_index('ix_code_chunks_repo_id_file_path', 'code_chunks', ['repo_id', 'file_path'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_repo_id_status', 'jobs', ['repo_id', 'status'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evaluations_job_id', 'evaluations', ['job_id'], unique=False)
    op.create_table('agent_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('evidence_snippets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_scores_agent_name'), 'agent_scores', ['agent_name'], unique=False)
    op.create_index('ix_agent_scores_evaluation_id_agent_name', 'agent_scores', ['evaluation_id', 'agent_name'], unique=False)
    op.create_table('developer_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('developer_github_username', sa.String(length=255), nullable=False),
    sa.Column('recommended_role', sa.String(length=100), nullable=False),
    sa.Column('suggested_team_name', sa.String(length=255), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_developer_recommendations_developer_github_username'), 'developer_recommendations', ['developer_github_username'], unique=False)
    op.create_index('ix_developer_recommendations_evaluation_id_username', 'developer_recommendations', ['evaluation_id', 'developer_github_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_developer_recommendations_evaluation_id_username', table_name='developer_recommendations')
    op.drop_index(op.f('ix_developer_recommendations_developer_github_username'), table_name='developer_recommendations')
    op.drop_table('developer_recommendations')
    op.drop_index('ix_agent_scores_evaluation_id_agent_name', table_name='agent_scores')
    op.drop_index(op.f('ix_agent_scores_agent_name'), table_name='agent_scores')
    op.drop_table('agent_scores')
    op.drop_index('ix_evaluations_job_id', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index('ix_jobs_repo_id_status', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_code_chunks_repo_id_file_path', table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_file_path'), table_name='code_chunks')
    op.drop_table('code_chunks')
    op.drop_index('ix_repos_user_id', table_name='repos')
    op.drop_index(op.f('ix_repos_repo_name'), table_name='repos')
    op.drop_index(op.f('ix_repos_github_repo_id'), table_name='repos')
    op.drop_table('repos')
    op.drop_index(op.f('ix_users_github_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
