/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as DashAskRouteImport } from './routes/_dash/ask'
import { Route as DashCompareRouteImport } from './routes/_dash/compare'
import { Route as DashEvaluationRouteImport } from './routes/_dash/evaluation'
import { Route as DashRecommendRouteImport } from './routes/_dash/recommend'
import { Route as DashReposRouteImport } from './routes/_dash/repos'
import { Route as DashSettingsRouteImport } from './routes/_dash/settings'
import { Route as DashTracesRouteImport } from './routes/_dash/traces'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const DashAskRoute = DashAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => DashRoute,
} as any)
const DashCompareRoute = DashCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => DashRoute,
} as any)
const DashEvaluationRoute = DashEvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => DashRoute,
} as any)
const DashRecommendRoute = DashRecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => DashRoute,
} as any)
const DashReposRoute = DashReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => DashRoute,
} as any)
const DashSettingsRoute = DashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashRoute,
} as any)
const DashTracesRoute = DashTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => DashRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof DashAskRoute
  '/compare': typeof DashCompareRoute
  '/evaluation': typeof DashEvaluationRoute
  '/recommend': typeof DashRecommendRoute
  '/repos': typeof DashReposRoute
  '/settings': typeof DashSettingsRoute
  '/traces': typeof DashTracesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof DashAskRoute
  '/compare': typeof DashCompareRoute
  '/evaluation': typeof DashEvaluationRoute
  '/recommend': typeof DashRecommendRoute
  '/repos': typeof DashReposRoute
  '/settings': typeof DashSettingsRoute
  '/traces': typeof DashTracesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/_dash/ask': typeof DashAskRoute
  '/_dash/compare': typeof DashCompareRoute
  '/_dash/evaluation': typeof DashEvaluationRoute
  '/_dash/recommend': typeof DashRecommendRoute
  '/_dash/repos': typeof DashReposRoute
  '/_dash/settings': typeof DashSettingsRoute
  '/_dash/traces': typeof DashTracesRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/compare'
    | '/evaluation'
    | '/recommend'
    | '/repos'
    | '/settings'
    | '/traces'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/compare'
    | '/evaluation'
    | '/recommend'
    | '/repos'
    | '/settings'
    | '/traces'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/_dash/ask'
    | '/_dash/compare'
    | '/_dash/evaluation'
    | '/_dash/recommend'
    | '/_dash/repos'
    | '/_dash/settings'
    | '/_dash/traces'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/ask': {
      id: '/_dash/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof DashAskRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/compare': {
      id: '/_dash/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof DashCompareRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/evaluation': {
      id: '/_dash/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof DashEvaluationRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/recommend': {
      id: '/_dash/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof DashRecommendRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/repos': {
      id: '/_dash/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof DashReposRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/settings': {
      id: '/_dash/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashSettingsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/traces': {
      id: '/_dash/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof DashTracesRouteImport
      parentRoute: typeof DashRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashRouteChildren {
  DashAskRoute: typeof DashAskRoute
  DashCompareRoute: typeof DashCompareRoute
  DashEvaluationRoute: typeof DashEvaluationRoute
  DashRecommendRoute: typeof DashRecommendRoute
  DashReposRoute: typeof DashReposRoute
  DashSettingsRoute: typeof DashSettingsRoute
  DashTracesRoute: typeof DashTracesRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAskRoute: DashAskRoute,
  DashCompareRoute: DashCompareRoute,
  DashEvaluationRoute: DashEvaluationRoute,
  DashRecommendRoute: DashRecommendRoute,
  DashReposRoute: DashReposRoute,
  DashSettingsRoute: DashSettingsRoute,
  DashTracesRoute: DashTracesRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
